// <auto-generated />
using System;
using ErrosSquad1.Infra.Data.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ErrosSquad1.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ErrosSquad1.Dominio.Entidades.Ambiente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("ambiente");
                });

            modelBuilder.Entity("ErrosSquad1.Dominio.Entidades.Erro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataHora")
                        .HasColumnName("data_hora");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasColumnName("detalhe")
                        .HasMaxLength(2000);

                    b.Property<int>("IdAmbiente")
                        .HasColumnName("id_ambiente");

                    b.Property<int>("IdNivel")
                        .HasColumnName("id_nivel");

                    b.Property<int>("IdUsuario")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnName("origem")
                        .HasMaxLength(16);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)))
                        .HasColumnName("status")
                        .HasMaxLength(1);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("titulo")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("IdAmbiente");

                    b.HasIndex("IdNivel");

                    b.HasIndex("IdUsuario");

                    b.ToTable("erro");
                });

            modelBuilder.Entity("ErrosSquad1.Dominio.Entidades.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("nivel");
                });

            modelBuilder.Entity("ErrosSquad1.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasMaxLength(100);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("senha")
                        .HasMaxLength(30);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnName("token")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("ErrosSquad1.Dominio.Entidades.Erro", b =>
                {
                    b.HasOne("ErrosSquad1.Dominio.Entidades.Ambiente", "Ambiente")
                        .WithMany("Erros")
                        .HasForeignKey("IdAmbiente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ErrosSquad1.Dominio.Entidades.Nivel", "Nivel")
                        .WithMany("Erros")
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ErrosSquad1.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Erros")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
